import type { ResearchNodeDef } from '../types'

/**
 * Full research catalog. Trunks are visual columns; prereqs define edges.
 * Keep IDs stable — sim gates reference them.
 */
export const RESEARCH_NODES: ResearchNodeDef[] = [
  // ─── INFERENCE / SYSTEMS ─────────────────────────────────
  {
    id: 'sys_batching',
    trunk: 'inference',
    name: 'Continuous Batching',
    description: 'Pack requests. Big jump in usable inference FLOPS.',
    costPfDays: 8,
    daysMin: 4,
    prereqs: [],
    effects: { utilCap: 0.08, servingEfficiency: 0.15 },
  },
  {
    id: 'sys_paged_attn',
    trunk: 'inference',
    name: 'Paged Attention',
    description: 'KV cache without fragmentation. Higher concurrency.',
    costPfDays: 14,
    daysMin: 5,
    prereqs: ['sys_batching'],
    effects: { utilCap: 0.06, servingEfficiency: 0.12 },
  },
  {
    id: 'sys_quant',
    trunk: 'inference',
    name: 'INT8 Quantization',
    description: 'Lower precision serving. More tokens per watt.',
    costPfDays: 12,
    daysMin: 5,
    prereqs: ['sys_batching'],
    effects: { servingEfficiency: 0.2, utilCap: 0.05 },
  },
  {
    id: 'sys_fp8',
    trunk: 'inference',
    name: 'FP8 Runtime Stack',
    description: 'Scaled E4M3/E5M2 inference on Hopper-class hardware.',
    costPfDays: 22,
    daysMin: 7,
    prereqs: ['sys_quant'],
    effects: { servingEfficiency: 0.22, utilCap: 0.04 },
  },
  {
    id: 'sys_int4',
    trunk: 'inference',
    name: 'INT4 Calibration Runtime',
    description: 'Calibrated four-bit deployment artifacts with domain-aware evaluations.',
    costPfDays: 26,
    daysMin: 8,
    prereqs: ['sys_quant', 'data_eval'],
    effects: { servingEfficiency: 0.16 },
    riskLevel: 'elevated',
  },
  {
    id: 'sys_nvfp4_runtime',
    trunk: 'inference',
    name: 'NVFP4 Serving Kernels',
    description: 'Blackwell-native microscaled FP4 serving and calibration.',
    costPfDays: 46,
    daysMin: 13,
    prereqs: ['sys_fp8', 'sys_kernels', 'si_arch'],
    effects: { servingEfficiency: 0.2, utilCap: 0.03 },
    riskLevel: 'high',
  },
  {
    id: 'sys_bitnet_runtime',
    trunk: 'inference',
    name: 'Ternary Inference Runtime',
    description: 'Packed 1.58-bit weights and specialized BitLinear kernels.',
    costPfDays: 42,
    daysMin: 12,
    prereqs: ['dense_bitnet', 'sys_kernels'],
    effects: { servingEfficiency: 0.24 },
    riskLevel: 'elevated',
  },
  {
    id: 'sys_spec_decode',
    trunk: 'inference',
    name: 'Speculative Decoding',
    description: 'Draft model speeds up generation.',
    costPfDays: 20,
    daysMin: 7,
    prereqs: ['sys_quant'],
    effects: { servingEfficiency: 0.25 },
  },
  {
    id: 'sys_medusa',
    trunk: 'inference',
    name: 'Medusa Decode Heads',
    description: 'Attach parallel auxiliary decode heads to a frozen language model and verify their token tree in one pass.',
    costPfDays: 28,
    daysMin: 9,
    prereqs: ['sys_spec_decode'],
    effects: { servingEfficiency: 0.18 },
  },
  {
    id: 'sys_gqa',
    trunk: 'inference',
    name: 'GQA / MQA Attention',
    description: 'Share key/value heads across query groups to shrink KV memory and improve long-context decode throughput.',
    costPfDays: 24,
    daysMin: 8,
    prereqs: ['sys_paged_attn', 'dense_basics'],
    effects: { servingEfficiency: 0.15, utilCap: 0.04, trainEfficiency: 0.03 },
  },
  {
    id: 'sys_vllm',
    trunk: 'inference',
    name: 'vLLM Production Runtime',
    description: 'Combine PagedAttention, continuous batching, prefix reuse, and scheduler telemetry in a production serving engine.',
    costPfDays: 30,
    daysMin: 9,
    prereqs: ['sys_paged_attn', 'sys_prefix', 'sys_compile'],
    effects: { servingEfficiency: 0.18, utilCap: 0.07 },
  },
  {
    id: 'sys_disagg',
    trunk: 'inference',
    name: 'Prefill/Decode Disagg',
    description: 'Specialize hardware roles. Near-production util.',
    costPfDays: 35,
    daysMin: 10,
    prereqs: ['sys_spec_decode', 'sys_paged_attn'],
    effects: { utilCap: 0.12, servingEfficiency: 0.15 },
  },
  {
    id: 'sys_prefix',
    trunk: 'inference',
    name: 'Prefix Caching',
    description: 'Reuse system prompts across sessions.',
    costPfDays: 16,
    daysMin: 5,
    prereqs: ['sys_paged_attn'],
    effects: { servingEfficiency: 0.1, utilCap: 0.03 },
  },
  {
    id: 'sys_router',
    trunk: 'inference',
    name: 'Model Router',
    description: 'Route easy traffic to small models. Save frontier capacity.',
    costPfDays: 24,
    daysMin: 8,
    prereqs: ['sys_batching'],
    effects: { servingEfficiency: 0.08, utilCap: 0.04 },
  },
  {
    id: 'sys_kernels',
    trunk: 'inference',
    name: 'Fused Kernels',
    description: 'Custom kernels squeeze remaining headroom.',
    costPfDays: 28,
    daysMin: 8,
    prereqs: ['sys_batching'],
    effects: { utilCap: 0.06, trainEfficiency: 0.1 },
  },
  {
    id: 'sys_compile',
    trunk: 'inference',
    name: 'Graph Compiler',
    description: 'Whole-graph fusion and static shapes.',
    costPfDays: 32,
    daysMin: 10,
    prereqs: ['sys_kernels'],
    effects: { utilCap: 0.05, servingEfficiency: 0.1, trainEfficiency: 0.06 },
  },
  {
    id: 'sys_kv_offload',
    trunk: 'inference',
    name: 'KV Offload / Tiered Cache',
    description: 'Park cold KV in host RAM/SSD. Raise concurrency without more HBM.',
    costPfDays: 26,
    daysMin: 8,
    prereqs: ['sys_paged_attn'],
    effects: { utilCap: 0.07, servingEfficiency: 0.14 },
  },
  {
    id: 'sys_tensor_rt',
    trunk: 'inference',
    name: 'Runtime Autotuner',
    description: 'Kernel pick + shape specialization per SKU. Squeeze idle SMs.',
    costPfDays: 30,
    daysMin: 9,
    prereqs: ['sys_compile'],
    effects: { servingEfficiency: 0.16, utilCap: 0.05 },
  },
  {
    id: 'sys_dist_cache',
    trunk: 'inference',
    name: 'Cluster Prefix Cache',
    description: 'Shared prompt cache across the fleet. Cut prefill PF.',
    costPfDays: 34,
    daysMin: 10,
    prereqs: ['sys_prefix', 'sys_disagg'],
    effects: { servingEfficiency: 0.18, utilCap: 0.04 },
  },
  {
    id: 'sys_load_shed',
    trunk: 'inference',
    name: 'Smart Load Shed',
    description: 'Graceful queue + priority so paid traffic keeps tokens under pressure.',
    costPfDays: 18,
    daysMin: 6,
    prereqs: ['sys_router'],
    effects: { servingEfficiency: 0.08, utilCap: 0.03 },
  },
  {
    id: 'sys_infer_asic',
    trunk: 'inference',
    name: 'Inference ASIC Kernels',
    description:
      'Custom decode datapaths and SRAM-resident KV. Push serving efficiency past general-purpose GPU stacks.',
    costPfDays: 55,
    daysMin: 14,
    prereqs: ['sys_tensor_rt', 'sys_dist_cache'],
    effects: { servingEfficiency: 0.22, utilCap: 0.04 },
    riskLevel: 'elevated',
  },
  {
    id: 'sys_kernel_fusion_v2',
    trunk: 'inference',
    name: 'Deep Kernel Fusion',
    description:
      'Whole-model fusion across attention, MLP, and sampling. Late-game tokens-per-watt.',
    costPfDays: 48,
    daysMin: 12,
    prereqs: ['sys_infer_asic', 'sys_medusa'],
    effects: { servingEfficiency: 0.2, utilCap: 0.03 },
    riskLevel: 'high',
  },

  // ─── TRAIN OPTIMIZATION ──────────────────────────────────
  {
    id: 'opt_checkpoint',
    trunk: 'optimize',
    name: 'Activation Checkpointing',
    description: 'Trade recompute for memory. Larger models fit.',
    costPfDays: 10,
    daysMin: 4,
    prereqs: [],
    effects: { trainEfficiency: 0.08 },
  },
  {
    id: 'opt_fsdp',
    trunk: 'optimize',
    name: 'DeepSpeed ZeRO-3 / FSDP',
    description: 'Shard parameters, gradients, and optimizer state across data-parallel workers with DeepSpeed ZeRO-3 or PyTorch FSDP.',
    costPfDays: 18,
    daysMin: 6,
    prereqs: ['opt_checkpoint'],
    effects: { trainEfficiency: 0.12 },
  },
  {
    id: 'opt_flash',
    trunk: 'optimize',
    name: 'Flash Attention',
    description: 'IO-aware attention. Train and serve both benefit.',
    costPfDays: 16,
    daysMin: 5,
    prereqs: ['opt_checkpoint'],
    effects: { trainEfficiency: 0.1, servingEfficiency: 0.08, utilCap: 0.03 },
  },
  {
    id: 'opt_pipeline',
    trunk: 'optimize',
    name: 'Pipeline Parallelism',
    description: 'Split layers across nodes for giant models.',
    costPfDays: 26,
    daysMin: 8,
    prereqs: ['opt_fsdp'],
    effects: { trainEfficiency: 0.1 },
  },
  {
    id: 'opt_data_pipe',
    trunk: 'optimize',
    name: 'Data Pipeline',
    description: 'Async loaders so GPUs never starve.',
    costPfDays: 12,
    daysMin: 4,
    prereqs: [],
    effects: { trainEfficiency: 0.08, utilCap: 0.03 },
  },
  {
    id: 'opt_fp16',
    trunk: 'optimize',
    name: 'FP16 Mixed Precision',
    description:
      'Half-precision tensor ops with FP32 master weights and loss scaling. Roughly doubles the FP32/TF32 starter recipe throughput and halves native weight memory.',
    costPfDays: 8,
    daysMin: 3,
    prereqs: [],
    effects: { trainEfficiency: 0.06 },
  },
  {
    id: 'opt_mixed',
    trunk: 'optimize',
    name: 'Mixed Precision Train',
    description: 'Stable BF16/FP16 AMP with master weights and loss scaling.',
    costPfDays: 14,
    daysMin: 5,
    prereqs: ['opt_flash', 'opt_fp16'],
    effects: { trainEfficiency: 0.12 },
  },
  {
    id: 'opt_fp8_train',
    trunk: 'optimize',
    name: 'FP8 Training Recipes',
    description: 'Hybrid FP8 forward/backward formats, scaling, kernels, and recovery.',
    costPfDays: 34,
    daysMin: 10,
    prereqs: ['opt_mixed', 'sys_fp8', 'sys_compile'],
    effects: { trainEfficiency: 0.08 },
    riskLevel: 'elevated',
  },
  {
    id: 'opt_te_fp8',
    trunk: 'optimize',
    name: 'Transformer Engine FP8',
    description: 'Use delayed scaling, amax histories, fused kernels, and per-layer format selection for stable Hopper FP8 training.',
    costPfDays: 42,
    daysMin: 12,
    prereqs: ['opt_fp8_train', 'sys_kernels'],
    effects: { trainEfficiency: 0.12, utilCap: 0.04 },
    riskLevel: 'elevated',
  },
  {
    id: 'opt_seq_parallel',
    trunk: 'optimize',
    name: 'Sequence Parallelism',
    description: 'Shard sequence-dimension activations and normalization work across tensor-parallel ranks to reduce memory pressure.',
    costPfDays: 28,
    daysMin: 9,
    prereqs: ['opt_fsdp', 'opt_pipeline'],
    effects: { trainEfficiency: 0.11, utilCap: 0.03 },
  },
  {
    id: 'opt_context_parallel',
    trunk: 'optimize',
    name: 'Context Parallelism',
    description: 'Partition long contexts across accelerators with ring attention and communication overlap.',
    costPfDays: 40,
    daysMin: 12,
    prereqs: ['opt_seq_parallel', 'dense_context', 'opt_overlap_comm'],
    effects: { trainEfficiency: 0.12, capabilityBonus: 1, overtrainCapBonus: 0.8 },
  },
  {
    id: 'opt_qlora',
    trunk: 'optimize',
    name: 'QLoRA Adaptation',
    description: 'Fine-tune low-rank adapters through frozen four-bit base weights with paged optimizer states.',
    costPfDays: 24,
    daysMin: 8,
    prereqs: ['opt_distill_stack', 'sys_int4'],
    effects: { trainEfficiency: 0.14, capabilityBonus: 1 },
  },
  {
    id: 'opt_nvfp4_train',
    trunk: 'optimize',
    name: 'Experimental NVFP4 Training',
    description: 'Blackwell-native FP4 recipes with strict scaling and evaluation gates.',
    costPfDays: 62,
    daysMin: 16,
    prereqs: ['opt_fp8_train', 'sys_nvfp4_runtime', 'data_eval'],
    effects: { trainEfficiency: 0.1, trainingStumbleRisk: 0.04 },
    riskLevel: 'high',
  },
  {
    id: 'opt_distill_stack',
    trunk: 'optimize',
    name: 'Distill Playbook',
    description: 'Cheaper student training from teachers.',
    costPfDays: 20,
    daysMin: 7,
    prereqs: ['opt_mixed', 'align_sft'],
    effects: { trainEfficiency: 0.08, capabilityBonus: 1 },
  },
  {
    id: 'opt_overlap_comm',
    trunk: 'optimize',
    name: 'Comm/Compute Overlap',
    description: 'Hide all-reduce behind matmuls. Better multi-node util.',
    costPfDays: 22,
    daysMin: 7,
    prereqs: ['opt_fsdp'],
    effects: { trainEfficiency: 0.1, utilCap: 0.04 },
  },
  {
    id: 'opt_grad_accum',
    trunk: 'optimize',
    name: 'Adaptive Grad Accum',
    description: 'Stable large effective batch without idle ranks.',
    costPfDays: 15,
    daysMin: 5,
    prereqs: ['opt_data_pipe'],
    effects: { trainEfficiency: 0.09 },
  },
  {
    id: 'opt_torch_compile',
    trunk: 'optimize',
    name: 'Train Graph Compile',
    description: 'Capture training graphs; less Python overhead, fuller SMs.',
    costPfDays: 24,
    daysMin: 8,
    prereqs: ['opt_mixed', 'sys_compile'],
    effects: { trainEfficiency: 0.11, utilCap: 0.03 },
  },
  {
    id: 'opt_compute_sched',
    trunk: 'optimize',
    name: 'Compute-Optimal Schedules',
    description:
      'Long-horizon LR schedules and epoch budgeting so extra FLOPs past the Chinchilla target keep converting into capability.',
    costPfDays: 32,
    daysMin: 10,
    prereqs: ['opt_torch_compile', 'data_eval'],
    effects: { trainEfficiency: 0.06, overtrainCapBonus: 1.5, capabilityBonus: 1 },
  },

  // ─── DATA (early game — roots sit at top of Data column) ─
  {
    id: 'data_mix',
    trunk: 'data',
    name: 'Mixture Engineering',
    description:
      'Unlock domain mix sliders when training — balance code/chat/law packs so evals actually move.',
    costPfDays: 8,
    daysMin: 3,
    prereqs: [],
    effects: { capabilityBonus: 2, dataFlywheel: 0.06 },
  },
  {
    id: 'data_clean',
    trunk: 'data',
    name: 'Data Cleaning',
    description: 'Dedup, filter, quality scoring for pretrain corpora.',
    costPfDays: 10,
    daysMin: 4,
    prereqs: [],
    effects: { capabilityBonus: 2, dataFlywheel: 0.05 },
  },
  {
    id: 'data_specialists',
    trunk: 'data',
    name: 'Specialist Curators',
    description:
      'Assign a model per corpus domain (code model → code packs, etc.). Same model on all domains is fine.',
    costPfDays: 12,
    daysMin: 4,
    prereqs: ['data_mix'],
    effects: { unlockCorpusSpecialists: true, capabilityBonus: 1, dataFlywheel: 0.06 },
  },
  {
    id: 'data_synth',
    trunk: 'data',
    name: 'Synthetic Generators',
    description:
      'AI data factories. Mid-tree unlock — needs clean pipelines + evals first. HQ synth needs a strong teacher; LQ is fast but can poison training.',
    costPfDays: 26,
    daysMin: 9,
    // Mid data trunk: mix → clean → eval → synth (not early free tokens)
    prereqs: ['data_mix', 'data_clean', 'data_eval'],
    effects: {
      capabilityBonus: 3,
      trainEfficiency: 0.05,
      dataFlywheel: 0.12,
      overtrainCapBonus: 0.8,
    },
  },
  {
    id: 'data_pref',
    trunk: 'data',
    name: 'Preference Farms',
    description: 'Scale human + AI preference labels for RLHF.',
    costPfDays: 18,
    daysMin: 6,
    prereqs: ['data_clean', 'align_sft'],
    effects: { rlhfQuality: 0.15, safetyBonus: 2 },
  },
  {
    id: 'data_eval',
    trunk: 'data',
    name: 'Eval Harness',
    description: 'Private evals catch regressions before ship.',
    costPfDays: 14,
    daysMin: 5,
    prereqs: ['data_clean'],
    effects: { capabilityBonus: 1, safetyBonus: 2, dataFlywheel: 0.05 },
  },
  {
    id: 'data_flywheel',
    trunk: 'data',
    name: 'Production Flywheel',
    description: 'Traffic → cleaned data → next train. Compounding edge.',
    costPfDays: 28,
    daysMin: 9,
    prereqs: ['data_synth', 'data_eval'],
    effects: { dataFlywheel: 0.25, capabilityBonus: 2 },
  },
  {
    id: 'data_self_train',
    trunk: 'data',
    name: 'Self-Training Loops',
    description:
      'Let frontier models generate, critique, and recycle their own curricula. Fast capability compounding, but failures can reinforce themselves.',
    costPfDays: 42,
    daysMin: 12,
    prereqs: ['data_synth', 'data_eval'],
    minResearchers: 12,
    cashBurnMult: 1.35,
    riskLevel: 'high',
    effects: {
      capabilityBonus: 6,
      trainEfficiency: 0.12,
      dataFlywheel: 0.18,
      trainingBreakthroughBias: 0.1,
      trainingStumbleRisk: 0.07,
      trainingSafetyPenalty: 5,
      overtrainCapBonus: 1.5,
    },
  },
  {
    id: 'data_web',
    trunk: 'data',
    name: 'Web-Scale Crawl Ops',
    description: 'Legal, filtered web data at frontier volume.',
    costPfDays: 30,
    daysMin: 10,
    prereqs: ['data_mix', 'data_clean'],
    effects: { capabilityBonus: 4, dataFlywheel: 0.1 },
  },

  // ─── HARDWARE / FACILITY ─────────────────────────────────
  {
    id: 'sys_cooling',
    trunk: 'hardware',
    name: 'Liquid Cooling',
    description: 'Better PUE — more chips per megawatt.',
    costPfDays: 18,
    daysMin: 6,
    prereqs: [],
    effects: { energyPue: -0.15 },
  },
  {
    id: 'hw_power',
    trunk: 'hardware',
    name: 'Power Topology',
    description: 'PDU design and load balancing across halls.',
    costPfDays: 14,
    daysMin: 5,
    prereqs: [],
    effects: { energyPue: -0.08, utilCap: 0.02 },
  },
  {
    id: 'hw_network',
    trunk: 'hardware',
    name: 'Cluster Fabric',
    description: 'IB/RoCE tuning for multi-node train.',
    costPfDays: 20,
    daysMin: 7,
    prereqs: ['hw_power'],
    effects: { trainEfficiency: 0.1, utilCap: 0.03 },
  },
  {
    id: 'hw_storage',
    trunk: 'hardware',
    name: 'Checkpoint Storage',
    description: 'Fast parallel FS for checkpoints and datasets.',
    costPfDays: 16,
    daysMin: 5,
    prereqs: ['hw_power'],
    effects: { trainEfficiency: 0.06 },
  },
  {
    id: 'hw_immersion',
    trunk: 'hardware',
    name: 'Immersion Cooling',
    description: 'Extreme density racks. Late-game PUE.',
    costPfDays: 36,
    daysMin: 12,
    prereqs: ['sys_cooling', 'hw_network'],
    effects: { energyPue: -0.12, utilCap: 0.04 },
  },
  {
    id: 'si_arch',
    trunk: 'hardware',
    name: 'Accelerator Architecture',
    description: 'In-house chip design. Opens custom silicon.',
    costPfDays: 40,
    daysMin: 12,
    prereqs: ['sys_kernels'],
    effects: { chipDiscount: 0.05, fabSpeed: 0.1 },
  },
  {
    id: 'si_packaging',
    trunk: 'hardware',
    name: 'Advanced Packaging',
    description: 'Better interconnect on bought and custom silicon.',
    costPfDays: 50,
    daysMin: 15,
    prereqs: ['si_arch'],
    effects: { utilCap: 0.04, chipDiscount: 0.08, fabSpeed: 0.1 },
  },
  {
    id: 'si_hbm_stack',
    trunk: 'hardware',
    name: 'HBM Fabric Co-design',
    description: 'Wide memory fabric for training arrays and long-context serving.',
    costPfDays: 46,
    daysMin: 14,
    prereqs: ['si_arch'],
    effects: { trainEfficiency: 0.05, fabSpeed: 0.05 },
  },
  {
    id: 'si_infer_asic',
    trunk: 'hardware',
    name: 'Decode ASIC Blocks',
    description: 'On-die KV cache and decode pipelines for high token throughput.',
    costPfDays: 44,
    daysMin: 13,
    prereqs: ['si_arch', 'sys_paged_attn'],
    effects: { servingEfficiency: 0.08, fabSpeed: 0.05 },
  },
  {
    id: 'si_chiplets',
    trunk: 'hardware',
    name: 'Chiplet Mesh',
    description: 'Reusable compute and I/O tiles improve yield and design flexibility.',
    costPfDays: 58,
    daysMin: 17,
    prereqs: ['si_packaging'],
    effects: { fabSpeed: 0.12, chipDiscount: 0.04 },
  },
  {
    id: 'si_photonic_io',
    trunk: 'hardware',
    name: 'Photonic Scale-out I/O',
    description: 'Optical links cut communication power across giant training pods.',
    costPfDays: 72,
    daysMin: 20,
    prereqs: ['si_chiplets', 'hw_network'],
    effects: { energyPue: -0.04, fabSpeed: 0.08 },
  },
  {
    id: 'si_fab_ops',
    trunk: 'hardware',
    name: 'Fab Ops Playbook',
    description: 'Yield ramps faster; fewer tape-out disasters.',
    costPfDays: 45,
    daysMin: 14,
    prereqs: ['si_arch'],
    effects: { fabSpeed: 0.2, chipDiscount: 0.03 },
  },
  {
    id: 'si_moe_npu',
    trunk: 'hardware',
    name: 'Sparse NPU ISA',
    description: 'Custom kernels for MoE on your silicon.',
    costPfDays: 55,
    daysMin: 16,
    prereqs: ['si_packaging', 'moe_serve'],
    effects: { moeInferMult: 0.7, fabSpeed: 0.05 },
  },

  // ─── DENSE ───────────────────────────────────────────────
  {
    id: 'dense_basics',
    trunk: 'dense',
    name: 'Dense Scaling Laws',
    description:
      'Every parameter learns on every token: stable, predictable quality at small and medium scale, but training and serving activate the full model.',
    costPfDays: 10,
    daysMin: 4,
    prereqs: [],
    effects: { unlockFamily: 'dense', capabilityBonus: 2, trainEfficiency: 0.05 },
  },
  {
    id: 'dense_opt',
    trunk: 'dense',
    name: 'Better Optimizers',
    description:
      'AdamW variants and schedule tuning reach the dense blueprint wall with less wasted compute; they do not raise that fixed frontier.',
    costPfDays: 16,
    daysMin: 5,
    prereqs: ['dense_basics'],
    effects: { capabilityBonus: 3, trainEfficiency: 0.1 },
  },
  {
    id: 'dense_context',
    trunk: 'dense',
    name: 'Long Context',
    description:
      '128k+ context wins document-heavy enterprise work, while KV memory and decode latency make every long request more expensive.',
    costPfDays: 24,
    daysMin: 8,
    prereqs: ['dense_opt'],
    effects: { capabilityBonus: 4, denseInferMult: 1.05 },
  },
  {
    id: 'dense_mtp',
    trunk: 'dense',
    name: 'Training-Time MTP',
    description:
      'Auxiliary future-token objectives improve planning and sample efficiency, at the cost of extra training heads and a less stable recipe.',
    costPfDays: 34,
    daysMin: 10,
    prereqs: ['dense_opt', 'data_eval'],
    effects: { capabilityBonus: 3, trainEfficiency: 0.05, trainingBreakthroughBias: 0.025 },
    riskLevel: 'elevated',
  },
  {
    id: 'dense_bitnet',
    trunk: 'dense',
    name: 'Ternary Architectures',
    description:
      'Native 1.58-bit weights can slash deployment memory, but demand a new training recipe and risk quality regressions near the frontier.',
    costPfDays: 38,
    daysMin: 12,
    prereqs: ['dense_opt', 'opt_mixed', 'data_eval'],
    effects: { capabilityBonus: 1 },
    riskLevel: 'high',
  },
  {
    id: 'dense_synth',
    trunk: 'dense',
    name: 'Dense Synthetic Loop',
    description:
      'Verified self-play stretches scarce data toward the dense wall; repeated unverified generations amplify blind spots instead.',
    costPfDays: 30,
    daysMin: 9,
    prereqs: ['dense_context', 'data_synth'],
    effects: { capabilityBonus: 5, trainEfficiency: 0.08 },
  },
  {
    id: 'dense_frontier',
    trunk: 'dense',
    name: 'Frontier Dense Stack',
    description:
      'Push pure dense to its fixed gameplay blueprint frontier. Every parameter stays active, so crossing the wall needs distillation or a different architecture.',
    costPfDays: 50,
    daysMin: 14,
    prereqs: ['dense_synth', 'opt_pipeline'],
    effects: { capabilityBonus: 8, denseInferMult: 0.95 },
  },

  // ─── MoE ─────────────────────────────────────────────────
  {
    id: 'moe_basics',
    trunk: 'moe',
    name: 'Sparse Basics',
    description:
      'Add total learned capacity without activating every expert per token. The whole expert bank still consumes memory and routing adds failure modes.',
    costPfDays: 14,
    daysMin: 5,
    prereqs: ['dense_basics'],
    effects: { unlockFamily: 'moe', capabilityBonus: 1 },
  },
  {
    id: 'moe_routing',
    trunk: 'moe',
    name: 'Expert Routing v1',
    description:
      'Stable top-k routing chooses a cheap active path. Poor gates starve experts, drop tokens, and can collapse the run.',
    costPfDays: 18,
    daysMin: 6,
    prereqs: ['moe_basics'],
    effects: { capabilityBonus: 3, moeInferMult: 0.85 },
  },
  {
    id: 'moe_balance',
    trunk: 'moe',
    name: 'Load Balance',
    description:
      'Auxiliary balance losses keep experts learning evenly, trading some specialization freedom for fewer hot spots and failed runs.',
    costPfDays: 22,
    daysMin: 7,
    prereqs: ['moe_routing'],
    effects: { capabilityBonus: 3, trainEfficiency: 0.08, moeInferMult: 0.9 },
  },
  {
    id: 'moe_parallel',
    trunk: 'moe',
    name: 'Expert Parallelism',
    description:
      'Shard experts across the cluster to scale total capacity; all-to-all traffic turns network quality into a hard training bottleneck.',
    costPfDays: 28,
    daysMin: 9,
    prereqs: ['moe_balance', 'opt_fsdp'],
    effects: { capabilityBonus: 4, trainEfficiency: 0.1 },
  },
  {
    id: 'moe_upcycle',
    trunk: 'moe',
    name: 'Dense→MoE Upcycling',
    description:
      'Convert a dense checkpoint into a sparse giant faster than training cold, but inherit teacher blind spots and initially redundant experts.',
    costPfDays: 32,
    daysMin: 10,
    prereqs: ['moe_parallel', 'dense_opt'],
    effects: { capabilityBonus: 5, trainEfficiency: 0.12 },
  },
  {
    id: 'moe_special',
    trunk: 'moe',
    name: 'Expert Specialization',
    description:
      'Domain experts raise coding and reasoning capacity, while skewed traffic can leave rare experts weak and general requests inconsistent.',
    costPfDays: 36,
    daysMin: 11,
    prereqs: ['moe_upcycle'],
    effects: { capabilityBonus: 6, moeInferMult: 0.8 },
  },
  {
    id: 'moe_hier',
    trunk: 'moe',
    name: 'Hierarchical MoE',
    description:
      'A higher blueprint frontier per active FLOP, offset by compounded routing, communication, and expert-residency complexity.',
    costPfDays: 45,
    daysMin: 13,
    prereqs: ['moe_special'],
    effects: { capabilityBonus: 7, moeInferMult: 0.72 },
  },
  {
    id: 'moe_serve',
    trunk: 'moe',
    name: 'MoE Speculative Decode',
    description:
      'Exploit the cheap active path during decode. Small batches still suffer unless routing, networking, and expert residency are coordinated.',
    costPfDays: 40,
    daysMin: 12,
    prereqs: ['moe_balance', 'sys_spec_decode'],
    effects: { servingEfficiency: 0.12, moeInferMult: 0.75 },
  },
  {
    id: 'moe_cache',
    trunk: 'moe',
    name: 'Shared Expert Cache',
    description:
      'Keep hot experts resident for strong margins on repeatable traffic; cold or diverse routing still pays full memory and transfer costs.',
    costPfDays: 48,
    daysMin: 14,
    prereqs: ['moe_hier', 'moe_serve'],
    effects: { moeInferMult: 0.65, utilCap: 0.05 },
  },

  // ─── ALIGNMENT ───────────────────────────────────────────
  {
    id: 'align_sft',
    trunk: 'alignment',
    name: 'Supervised Fine-Tuning',
    description: 'Instruction following basics.',
    costPfDays: 8,
    daysMin: 3,
    prereqs: [],
    effects: { safetyBonus: 2, rlhfQuality: 0.1 },
  },
  {
    id: 'align_rlhf',
    trunk: 'alignment',
    name: 'RLHF Pipeline',
    description: 'Preference data turns capability into products.',
    costPfDays: 16,
    daysMin: 6,
    prereqs: ['align_sft'],
    effects: { safetyBonus: 5, rlhfQuality: 0.25 },
  },
  {
    id: 'align_dpo',
    trunk: 'alignment',
    name: 'Direct Preference Optimization',
    description: 'Optimize chosen-versus-rejected responses directly against a reference policy without a separate reward-model loop.',
    costPfDays: 22,
    daysMin: 7,
    prereqs: ['align_sft', 'data_pref'],
    effects: { rlhfQuality: 0.12, capabilityBonus: 2, trainEfficiency: 0.05 },
  },
  {
    id: 'align_grpo',
    trunk: 'alignment',
    name: 'Group Relative Policy Optimization',
    description: 'Use group-relative sampled rewards for verifiable reasoning tasks without a learned value critic.',
    costPfDays: 36,
    daysMin: 11,
    prereqs: ['align_dpo', 'align_process', 'domain_math'],
    effects: {
      rlhfQuality: 0.1,
      capabilityBonus: 4,
      benchmarkBoost: { math: 5, coding: 3 },
      trainingBreakthroughBias: 0.035,
      overtrainCapBonus: 1.2,
    },
    riskLevel: 'elevated',
  },
  {
    id: 'align_process',
    trunk: 'alignment',
    name: 'Process Reward Models',
    description: 'Reward reasoning steps, not just answers.',
    costPfDays: 24,
    daysMin: 8,
    prereqs: ['align_rlhf'],
    effects: {
      safetyBonus: 3,
      capabilityBonus: 3,
      rlhfQuality: 0.15,
      overtrainCapBonus: 1.0,
    },
  },
  {
    id: 'align_redteam',
    trunk: 'alignment',
    name: 'Red-Teaming Ops',
    description: 'Enterprise trusts you. Consumer subs stick.',
    costPfDays: 20,
    daysMin: 7,
    prereqs: ['align_rlhf'],
    effects: { safetyBonus: 6, rlhfQuality: 0.1 },
  },
  {
    id: 'align_const',
    trunk: 'alignment',
    name: 'Constitutional AI',
    description: 'Principle-based self-critique loops.',
    costPfDays: 22,
    daysMin: 7,
    prereqs: ['align_rlhf'],
    effects: { safetyBonus: 4, rlhfQuality: 0.12 },
  },
  {
    id: 'align_agent_redteam',
    trunk: 'alignment',
    name: 'Agentic Red Teaming',
    description:
      'Autonomous agents attack, adapt, and self-play against live scaffolds. Unusually strong reasoning upside with a real chance of unsafe learned strategies.',
    costPfDays: 46,
    daysMin: 13,
    prereqs: ['align_process', 'align_redteam'],
    minResearchers: 16,
    cashBurnMult: 1.5,
    riskLevel: 'high',
    effects: {
      capabilityBonus: 7,
      trainEfficiency: 0.08,
      servingEfficiency: 0.06,
      safetyBonus: -3,
      trainingBreakthroughBias: 0.13,
      trainingStumbleRisk: 0.11,
      trainingSafetyPenalty: 8,
    },
  },

  // ─── MULTIMODAL ──────────────────────────────────────────
  {
    id: 'mm_vision',
    trunk: 'multimodal',
    name: 'Vision Encoders',
    description:
      'Image understanding adds visual grounding, but needs carefully aligned captions and far more aggressive quality filtering than text.',
    costPfDays: 22,
    daysMin: 8,
    prereqs: ['dense_basics'],
    effects: { unlockFamily: 'diffusion', capabilityBonus: 2 },
  },
  {
    id: 'mm_diff',
    trunk: 'multimodal',
    name: 'Latent Diffusion',
    description:
      'Launch image generation with a specialist quality ceiling; high-volume noisy media data raises pruning, rights, and evaluation costs.',
    costPfDays: 28,
    daysMin: 9,
    prereqs: ['mm_vision'],
    effects: { capabilityBonus: 3 },
  },
  {
    id: 'mm_video',
    trunk: 'multimodal',
    name: 'Video Temporal Models',
    description:
      'Temporal generation opens a premium product line, but long outputs make training, evaluation, and serving exceptionally power hungry.',
    costPfDays: 55,
    daysMin: 16,
    prereqs: ['mm_diff', 'sys_cooling'],
    effects: { unlockFamily: 'video', capabilityBonus: 4 },
  },
  {
    id: 'mm_omni',
    trunk: 'multimodal',
    name: 'Omni Stack',
    description:
      'Unify language, media, tools, and agents for the highest base blueprint frontier. Cross-modal transfer helps, but data demand, modality interference, output tokens, and hosting cost all surge.',
    costPfDays: 60,
    daysMin: 18,
    prereqs: ['mm_video', 'align_process'],
    effects: { unlockFamily: 'omni', capabilityBonus: 6 },
  },
  {
    id: 'mm_closed_loop_research',
    trunk: 'multimodal',
    name: 'Closed-Loop Autonomous Research',
    description:
      'Omni-only frontier unlock: agents propose experiments, generate traces, and retain only independently verified gains. It grants no passive capability—each loop needs fresh real data, verifier capacity, agent teams, and heavy train-plus-inference compute; weak checks or recursive synthetic reuse can bank regressions.',
    costPfDays: 120,
    daysMin: 32,
    prereqs: [
      'mm_omni',
      'align_agent_redteam',
      'data_self_train',
      'domain_agents',
      'opt_compute_sched',
      'sys_kernel_fusion_v2',
    ],
    minResearchers: 32,
    cashBurnMult: 2.2,
    riskLevel: 'high',
    effects: { unlockClosedLoopResearch: true },
  },

  // ─── DOMAIN ──────────────────────────────────────────────
  {
    id: 'domain_coding',
    trunk: 'domain',
    name: 'Code Specialist',
    description: 'Repo-level data + unit-test RL.',
    costPfDays: 26,
    daysMin: 8,
    prereqs: ['dense_opt', 'align_sft'],
    effects: { capabilityBonus: 2, benchmarkBoost: { coding: 14, agents: 4 } },
  },
  {
    id: 'domain_math',
    trunk: 'domain',
    name: 'Math & Formal',
    description: 'Proof-oriented data and process rewards.',
    costPfDays: 24,
    daysMin: 8,
    prereqs: ['align_process'],
    effects: { capabilityBonus: 2, benchmarkBoost: { math: 14, mmlu: 3, science: 4 } },
  },
  {
    id: 'domain_vision',
    trunk: 'domain',
    name: 'Vision Eval Suite',
    description: 'High-res perception and document VQA.',
    costPfDays: 28,
    daysMin: 9,
    prereqs: ['mm_vision'],
    effects: { benchmarkBoost: { vision: 16, agents: 3 } },
  },
  {
    id: 'domain_law',
    trunk: 'domain',
    name: 'Legal Corpus',
    description: 'Legal segment wins. Demands strong safety.',
    costPfDays: 32,
    daysMin: 10,
    prereqs: ['align_rlhf', 'dense_context'],
    effects: { safetyBonus: 3, benchmarkBoost: { law: 20, safety: 4, mmlu: 2 } },
  },
  {
    id: 'domain_science',
    trunk: 'domain',
    name: 'Scientific Pretrain',
    description: 'Papers, protocols, STEM reasoning.',
    costPfDays: 22,
    daysMin: 7,
    prereqs: ['dense_basics', 'align_sft'],
    effects: { benchmarkBoost: { science: 12, math: 4, mmlu: 3 } },
  },
  {
    id: 'domain_health',
    trunk: 'domain',
    name: 'Clinical Knowledge',
    description: 'Healthcare AI. Safety-critical.',
    costPfDays: 36,
    daysMin: 12,
    prereqs: ['align_redteam', 'domain_science'],
    effects: { safetyBonus: 5, benchmarkBoost: { health: 22, safety: 6, science: 3 } },
  },
  {
    id: 'domain_multi',
    trunk: 'domain',
    name: 'Multilingual',
    description: 'Tokenizer + parallel data for global products.',
    costPfDays: 20,
    daysMin: 6,
    prereqs: ['dense_basics'],
    effects: { benchmarkBoost: { multilingual: 16, mmlu: 2 } },
  },
  {
    id: 'domain_agents',
    trunk: 'domain',
    name: 'Tool-Use Gym',
    description: 'Browser, code exec, API tool trajectories.',
    costPfDays: 30,
    daysMin: 10,
    prereqs: ['align_sft', 'domain_coding'],
    effects: { benchmarkBoost: { agents: 16, coding: 4 } },
  },

  // ─── ORG ─────────────────────────────────────────────────
  {
    id: 'org_talent',
    trunk: 'org',
    name: 'Research Culture',
    description: 'Attract better talent; research and train speed up.',
    costPfDays: 18,
    daysMin: 6,
    prereqs: [],
    effects: { talentAttract: 0.15, trainEfficiency: 0.05 },
  },
  {
    id: 'org_data',
    trunk: 'org',
    name: 'Data Org',
    description: 'Cross-team data flywheel ownership.',
    costPfDays: 22,
    daysMin: 7,
    prereqs: ['align_sft'],
    effects: { dataFlywheel: 0.2, rlhfQuality: 0.08 },
  },
  {
    id: 'org_labs',
    trunk: 'org',
    name: 'Lab Structure',
    description: 'Parallel research tracks without thrash.',
    costPfDays: 20,
    daysMin: 6,
    prereqs: ['org_talent'],
    effects: { talentAttract: 0.1, trainEfficiency: 0.04 },
  },
]

export function getResearchNode(id: string): ResearchNodeDef {
  const n = RESEARCH_NODES.find((r) => r.id === id)
  if (!n) throw new Error(`Unknown research ${id}`)
  return n
}

/** Column order on the tree — Data first so mix/specialists are on-screen immediately. */
export const RESEARCH_TRUNKS = [
  'data',
  'inference',
  'optimize',
  'hardware',
  'dense',
  'moe',
  'alignment',
  'multimodal',
  'domain',
  'org',
] as const

export const RESEARCH_BRANCHES = {
  architecture_scaling: {
    label: 'Architectures & scaling',
    trunks: ['dense', 'moe', 'multimodal'],
  },
  training_systems: {
    label: 'Training systems',
    trunks: ['optimize'],
  },
  data_synthetic: {
    label: 'Data & synthetic methods',
    trunks: ['data'],
  },
  posttrain_eval_trust: {
    label: 'Post-training, evaluation & trust',
    trunks: ['alignment', 'domain'],
  },
  inference_efficiency: {
    label: 'Inference efficiency',
    trunks: ['inference'],
  },
  hardware_facilities: {
    label: 'Hardware & facilities',
    trunks: ['hardware'],
  },
  research_operations: {
    label: 'Research operations',
    trunks: ['org'],
  },
} as const

export type ResearchBranchId = keyof typeof RESEARCH_BRANCHES

export function researchBranchForNode(nodeId: string): ResearchBranchId {
  const node = getResearchNode(nodeId)
  const match = Object.entries(RESEARCH_BRANCHES).find(([, branch]) =>
    (branch.trunks as readonly string[]).includes(node.trunk),
  )
  return (match?.[0] ?? 'research_operations') as ResearchBranchId
}

export type ResearchTrunkId = (typeof RESEARCH_TRUNKS)[number]

export const TRUNK_META: Record<
  ResearchTrunkId,
  { label: string; color: string; blurb: string }
> = {
  inference: { label: 'Inference', color: '#4da3ff', blurb: 'Serve more tokens per chip' },
  optimize: { label: 'Train opt', color: '#ffb020', blurb: 'Throughput & parallelism' },
  data: { label: 'Data', color: '#3dffc0', blurb: 'Corpora, synth, flywheels' },
  hardware: { label: 'Hardware', color: '#e8e6e1', blurb: 'Cooling, fabric, silicon' },
  dense: { label: 'Dense', color: '#f472b6', blurb: 'Classic scaling path' },
  moe: { label: 'MoE', color: '#a78bfa', blurb: 'Sparse specialists' },
  alignment: { label: 'Alignment', color: '#34d399', blurb: 'SFT, RLHF, safety' },
  multimodal: { label: 'Multimodal', color: '#fb923c', blurb: 'Vision, video, omni' },
  domain: { label: 'Domain', color: '#38bdf8', blurb: 'Code, law, health…' },
  org: { label: 'Org', color: '#94a3b8', blurb: 'Talent & process' },
}

// Layout lives in researchLayout.ts so adding nodes never needs manual coordinates.
export {
  layoutResearchTree,
  layoutResearchTrunk,
  researchDepth,
  layoutHasOverlaps,
  RESEARCH_LAYOUT,
  type TreeLayoutNode,
  type TreeLayoutEdge,
  type ResearchTreeLayout,
} from './researchLayout'
